# Generated by Django 5.2 on 2025-05-03 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField()),
                ('base_price', models.IntegerField(verbose_name='Prix de base')),
                ('image', models.ImageField(blank=True, upload_to='services_lavage/')),
                ('available_place', models.PositiveIntegerField(default=5, verbose_name='Nombre de places disponibles')),
                ('last_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Dernière mise à jour')),
                ('created_on', models.DateField(auto_now_add=True, null=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Service',
            },
        ),
    ]
