# Generated by Django 5.2 on 2025-05-03 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('sex', models.PositiveSmallIntegerField(blank=True, choices=[('', 'Choisissez votre sexe'), (0, 'Masculin'), (1, 'Féminin')], null=True, verbose_name='Sexe')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('birth_date', models.DateField(verbose_name='Date de naissance')),
                ('phone_number', models.CharField(max_length=8, unique=True, verbose_name='Numéro de téléphone')),
                ('address', models.CharField(max_length=200, verbose_name='Adresse')),
                ('profile_picture', models.FileField(blank=True, null=True, upload_to='photo_profil/', verbose_name='Photo de profil')),
                ('last_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Dernière mise à jour')),
                ('created_on', models.DateField(auto_now_add=True, null=True, verbose_name='Date de création')),
                ('loyality_point', models.PositiveIntegerField(default=0, editable=False, verbose_name='Points de fidelité')),
                ('total_vehicle', models.PositiveIntegerField(default=0, editable=False, verbose_name='Nombre total de vehicule')),
                ('total_booking', models.PositiveIntegerField(default=0, editable=False, verbose_name='Nombre total de réservation')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Client',
                'constraints': [models.UniqueConstraint(fields=('user', 'last_name', 'first_name', 'birth_date', 'phone_number'), name='unique_customer')],
            },
        ),
    ]
