# Generated by Django 5.2 on 2025-05-03 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('employees', '0001_initial'),
        ('services', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('reference', models.CharField(max_length=20, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date et heure de création')),
                ('washing_date', models.DateTimeField(blank=True, null=True, verbose_name='Date et heure de lavage')),
                ('status', models.PositiveSmallIntegerField(choices=[('', 'Choisissez le statut'), (0, 'En attente'), (1, 'Confirmé'), (2, 'En cours'), (3, 'Terminé'), (4, 'Annulé'), (5, 'Payé')], default=0, verbose_name='Statut')),
                ('waiting_date', models.DateTimeField(blank=True, null=True, verbose_name='Date et heure lavage en attente')),
                ('acceptance_date', models.DateTimeField(blank=True, null=True, verbose_name='Date et heure lavage confirmé')),
                ('ongoing_date', models.DateTimeField(blank=True, null=True, verbose_name='Date et heure lavage en cours')),
                ('finishing_date', models.DateTimeField(blank=True, null=True, verbose_name='Date et heure lavage terminé')),
                ('cancelling_date', models.DateTimeField(blank=True, null=True, verbose_name='Date et heure lavage annulé')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='Date et heure lavage payé')),
                ('price', models.IntegerField(verbose_name='Prix du lavage')),
                ('cleaner', models.ForeignKey(limit_choices_to={'role': 1}, on_delete=django.db.models.deletion.CASCADE, related_name='reservations_realises', to='employees.employee', verbose_name='Laveur')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer', verbose_name='Client')),
                ('receptionist', models.ForeignKey(limit_choices_to={'role': 0}, on_delete=django.db.models.deletion.CASCADE, related_name='reservations_enregistres', to='employees.employee', verbose_name="Agent d'accueil")),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service', verbose_name='Service')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicle', verbose_name='Vehicule')),
            ],
        ),
    ]
