# Generated by Django 5.2 on 2025-05-03 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('brand', models.CharField(max_length=70, verbose_name='Marque')),
                ('model', models.CharField(max_length=70, verbose_name='Modele')),
                ('color', models.CharField(max_length=70, verbose_name='Couleur')),
                ('registrationNumber', models.CharField(max_length=10, unique=True, verbose_name='Immatriculation')),
                ('registration_certificate', models.FileField(upload_to='cartes_grises/')),
                ('last_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Dernière mise à jour')),
                ('created_on', models.DateField(auto_now_add=True, null=True, verbose_name='Date de création')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
            ],
            options={
                'verbose_name': 'Véhicule',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('vehicle_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vehicles.vehicle')),
                ('nb_places', models.PositiveIntegerField(default=5, verbose_name='Nombre de places')),
                ('nb_doors', models.PositiveIntegerField(default=4, verbose_name='Nombre de portes')),
            ],
            options={
                'verbose_name': 'Voiture',
            },
            bases=('vehicles.vehicle',),
        ),
        migrations.CreateModel(
            name='Motorcycle',
            fields=[
                ('vehicle_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vehicles.vehicle')),
                ('capacity', models.IntegerField(verbose_name='Capacite du moteur')),
            ],
            options={
                'verbose_name': 'Moto',
            },
            bases=('vehicles.vehicle',),
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.UniqueConstraint(fields=('brand', 'model', 'registrationNumber', 'color'), name='unique_vehicle'),
        ),
    ]
